### ISSUE TITLE
Possibly to add a option to adjust overlap size

### ISSUE THREAD

**Issue by james34602** [bewantbe/audio-analyzer-for-android#10]
With different overlap sample will have different smoothness and accuracy.

**Comment by bewantbe** [comment]
Will consider that.

But you should also aware that increase overlapping too much do not increase accuracy (smooth while essentially redundant), but increase computation cost.

50% overlap is a common practice that balance between time resolution and redundancy for Bartlett window and Hanning window.

**Comment by james34602** [comment]
Yes.
More overlap will destroy accuracy, but it wasn't so much. The Spectroid app in play store seems do the job.

**Comment by bewantbe** [comment]
Well, I'm persuaded, it seems that human eye prefers some redundancy. See figures below (50%, 75%, 87.5% overlap).

![swing-stft-overlap-50 0percent](https://cloud.githubusercontent.com/assets/4962979/24660754/68badfa8-1961-11e7-840c-dd6ecb539b96.png)

![swing-stft-overlap-75 0percent](https://cloud.githubusercontent.com/assets/4962979/24660757/6d019534-1961-11e7-8dae-86d371bef0fb.png)

![swing-stft-overlap-87 5percent](https://cloud.githubusercontent.com/assets/4962979/24660765/708b109a-1961-11e7-83f5-ef799b6040fe.png)

Octave scrip that generate these pic:

[test_stft_overlap.txt](https://github.com/bewantbe/audio-analyzer-for-android/files/893386/test_stft_overlap.txt)

**Comment by james34602** [comment]
Nice figure :D
More overlap less discontinuity for sure.

I have built a real time spectrum and spectrogram app based on Win32 API bitmap(not open source), it is able to adjust overlap size, and find that reasonable overlap adjustment will give nice spectrogram.
More overlap percentage is useful when you look at some spectrogram of a vibrato.

Sometimes you need accurate frequency measurement, you will reduce the overlap. It is better that overlap can be adjust in menu, you might need to allocate new buffer size each time you change overlap, depend on how you implement...

**Comment by bewantbe** [comment]
Added option for adjust overlapping. see commit 9574e23.

Not extensively tested, but should work.

**Comment by james34602** [comment]
Nice!
Probably close this issue
