### ISSUE TITLE
CalibrationLoad isnt found.

### ISSUE THREAD

**Issue by tf0054** [bewantbe/audio-analyzer-for-android#15]
On the master branch, it seems needing "CalibrationLoad", but the code wouldnt be commited.

We could use the code base 1837ed9656ddcd5869496c151fd79f242eb03998 on behalf of it, but itd be great if you update the master branch.

**Comment by bewantbe** [comment]
Wow, indeed, now it should fixed.

**Comment by TryGennai** [comment]
Thank you for your update!

**Comment by tf0054** [comment]
Thank you!
