### ISSUE TITLE
Ability to calculate hertz?

### ISSUE THREAD

**Issue by hksfho** [bewantbe/audio-analyzer-for-android#16]
I want to sang "do" "re" "me" to the microphone and show the hertz and dB

**Comment by james34602** [comment]
This app come with peak display. Peak will calculated right after FFT have been computed, in STFT class calculatePeak() was called by SamplingLoop class.
You know that musical note not have only one peak, so it will have second harmonic and etc...
Now log scale display is recommended, you will also turn on the cursor(tap on spectrum area and hold a few seconds) to select another frequency peak.

**Comment by bewantbe** [comment]
Thanks james for answering. If OP @hksfho has more questions, just open a new issue.
