### ISSUE TITLE
How can I detect frequency more than 10K

### ISSUE THREAD

**Issue by AmlanDwivedy** [bewantbe/audio-analyzer-for-android#2]
I was trying to listen the frequency more than human audible limit. How can I achieve that?

**Comment by bewantbe** [comment]
The key point is to increase the sampling rate.

   There is a button (possibly showing 8000), press it, a drop-down list will show "SAMPLE/S 8000 11025 44100" etc. Choose the highest one in the list, usually that is 48000.
   By choosing sampling rate 48000Hz, you cell phone will be able to hear up to 24kHz (48000/2). That 's slightly higher than audible limit of normal people.
   In the setting menu there is an item "Test&Show hardware's ability". Try it (takes a while), if it only list frequencies up to 48000, then that should be your cell phone's hardware limit.

If you definitely need really high frequency detection. You will need a good device. Possibly a computer with a good sound card (discrete or integrated) and a suitable microphone. Nowadays, it is normal for a not-too-bad sound card to do sampling at 96kHz.

**Comment by AmlanDwivedy** [comment]
Thanks Bewantbe,
   Thanks its working

Regards
Amlan.

**Comment by bewantbe** [comment]
Glad to hear that. AmlanDwivedy.

If there are still some problems, feel free to ask or discuss.
