### ISSUE TITLE
what is the meaning of the audio source id?

### ISSUE THREAD

**Issue by ArtemisZGL** [bewantbe/audio-analyzer-for-android#24]

**Comment by bewantbe** [comment]
Not sure what part of the source code or App UI you are referring to.
In general, the meaning of audio source id can be found in Android developer reference [MediaRecorder.AudioSource](https://developer.android.com/reference/android/media/MediaRecorder.AudioSource).

**Comment by bewantbe** [comment]
If your question got answered, shall we close this issue?

**Comment by ArtemisZGL** [comment]
yes, thanks a lot
