### ISSUE TITLE
A question about dB scale

### ISSUE THREAD

**Issue by FiluHalon** [bewantbe/audio-analyzer-for-android#4]
Hello,

I am using your Audio Spectrum Analyser and really appreciate your work - it is awesome!

Nevertheles, I have a question about changing dB scale to linear - is it possible? Can you kindly tell me if there is any way to change the original code and make the app to show y-axis values in linear scale instead of dBs?

Thank you very much. 

Yours sincerelly,
Filip

**Comment by bewantbe** [comment]
Hi Filip,

  That's easy I think. I will create a branch that demonstrate how to make this change temporary.

**Comment by FiluHalon** [comment]
Hello and thanks for your reply!

I really appreciate your help.

**Comment by bewantbe** [comment]
@FiluHalon 

Done! Try the branch linear-pow.

**Comment by FiluHalon** [comment]
Thank you very much!

**Comment by bewantbe** [comment]
This issue can be close.

And this feature won't be merged to mainline, since after I try it out, I feel it is not so useful, weak signal can't be seen.
