### ISSUE TITLE
Datatype of Samples?

### ISSUE THREAD

**Issue by nfsmaster208** [bewantbe/audio-analyzer-for-android#8]
I am first trying to figure out exactly where and how the program is interpreting the datastream from the Android sources. I have been considering enabling the remote_submix Audio Source, but in any case, it would be helpful if you may be able to point me in the direction of where the program is taking in the data stream and basically the pipeline for which the data travels. The goal is to be able to load and analyze audio files. Thank you!

**Comment by bewantbe** [comment]
The data process loop is located in `run()` in SamplingLoop.java (after commit c9e430b2  (Feb 06, 2017)), as well as the trigger of graphics refresh.

In every loop of `while (isRunning)`, it reads a chunk of audio samples
`record.read(audioSamples, 0, readChunkSize);`
, then "stream" it to STFT.java by
`stft.feedData(audioSamples, numOfReadShort);`
which calculates RMS and FFT whenever enough data is collected. The view is then informed by 
`activity.analyzerViews.update(spectrumDBcopy);`
 which ultimately calls `invalidate()` of the graphic view to request an update (automatically call the `AnalyzerGraphic.onDraw(Canvas c)`).

The code also contains a few custom audio sources, which is generated by `readTestData()` in SamplingLoop.java, and you can see usage in that while loop also. You might start from here to analyze an audio file, or write you own process loop, depending on you need.

The remote_submix Audio Source is not available to normal app, see https://developer.android.com/reference/android/media/MediaRecorder.AudioSource.html#REMOTE_SUBMIX.

**Comment by nfsmaster208** [comment]
@bewantbe Thank you for the response! I will look into the possibility of the custom process loop, as it does seem unusually convoluted to get remote_submix working.

@DSteve595 You and I can look here for potential collaboration on this project as well. :+1:

**Comment by bewantbe** [comment]
BTW, I saw a recent comment in the Play Store, is that you?

**Comment by nfsmaster208** [comment]
@bewantbe That indeed was me on another account I have. Thank you for the reply. I thought the app needed a review on the Store that reflected the current state of the app so far, and do completely appreciate your continued support in every way. You are doing a great service for the community, and I want to contribute as much as I can where possible to help support the app and that effort. Obviously, the timeline is not much of a concern, and I was also hoping raising the rating in the store which may rank the app a little higher on search, so more people can discover and use Audio Analyzer for Android.
